version: '1'

services:
  golden-ai-slack-bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "5g"
    environment:
      - AI_PROVIDER=${AI_PROVIDER}
      - AZURE_API_BASE=${AZURE_API_BASE}
      - AZURE_API_VERSION=${AZURE_API_VERSION}
      - AZURE_DEPLOYMENT_NAME=${AZURE_DEPLOYMENT_NAME}
      - HELICONE_API_KEY=${HELICONE_API_KEY}
      - LOG_LEVEL=${LOG_LEVEL}
      - OPENAI_API_BASE=${OPENAI_API_BASE}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_CHAT_ENABLE_SUMMARIZE=${OPENAI_CHAT_ENABLE_SUMMARIZE}
      - OPENAI_CHAT_MODEL=${OPENAI_CHAT_MODEL}
      - OPENAI_CHAT_NUM_OF_MESSAGES=${OPENAI_CHAT_NUM_OF_MESSAGES}
      - OPENAI_CHAT_SYSTEM_MESSAGE=${OPENAI_CHAT_SYSTEM_MESSAGE}
      - OPENAI_CHAT_TTL=${OPENAI_CHAT_TTL}
      - SLACK_APP_MENTION_QUOTE_USER_MESSAGE=${SLACK_APP_MENTION_QUOTE_USER_MESSAGE}
      - SLACK_APP_TOKEN=${SLACK_APP_TOKEN}
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
      - SLACK_SIGNING_SECRET=${SLACK_SIGNING_SECRET}
